<?php

include_once 'forms.php';
include_once 'functions.php';

/**
 * @file
 * This module provides a node type called 'Simple Content Type'
 */

/**
 * Fonction pour récupérer sous forme de tableau la date complète,
 * formatée correctement en FR, depuis un timestamp
 * indices 0 : jour en toute lettre, 1 : numéro du jour, 2 : mois, 3 : année
 * 
 * @date = timestamp
 */


/**
 * Implements hook_node_info().
 */
function osa_node_info() {
  // define our content type info
  $items['osa_affaire'] = array(
    'name' => t('Affaire'),
    'type' => 'osa_affaire',
    'base' => 'osa_affaire',
    'description' => t('Une nouvelle affaire à enregistrer'),
    'has_title' => '1',
    'title_label' => t('Affaire - Système OSA'),
    'has_body' => FALSE,
    'help' => t('Veuillez renseigner tous les champs.'),
  );
  $items['osa_client'] = array(
    'name' => t('Client'),
    'type' => 'osa_client',
    'base' => 'osa_client',
    'description' => t('Un nouveau client à enregistrer'),
    'has_title' => '1',
    'title_label' => t('Client - Système OSA'),
    'has_body' => FALSE,
    'help' => t('Veuillez renseigner tous les champs.'),
  );


  return $items;
}

/**
 * Implements hook_node_validate().
 */
function osa_node_validate($node, $form, &$form_state) {
  // if we're not validating one of our own get out of here
  if ($node->type == "osa_affaire") {
    
  }
  elseif ($node->type == 'osa_client') {
    
  }
  else {
    return;
  }
  // Check to see if email address is formatted correctly
//	if (isset($node->osa_textfield) && !valid_email_address($node->osa_textfield))  {
//		form_set_error('osa_textfield', t('Please enter a valid email address.'), NULL);
//	}
}

/**
 * Implement hook_node_insert()
 */
function osa_node_insert($node) {
  // if we're not inserting one of our own get out of here
  if ($node->type == 'osa_affaire') {
    global $user;
    $nid = $node->nid;
    $uid = $user->uid;

    // Passage des dates en TIMESTAMP pour ajout en BDD.
    // Pour cela, on instancie la classe DateTime en créant nos objets
    // dateDebut, Fin, PremierContact
    // On récupère ensuite une date correctement formaté à l'aide de l'array créé
    // par drupal. On applique à cet object la méthode getTimestamp pour retourner
    // ce qu'on l'on veut : un timestamp en bonne et due forme.


    $dateDebut = new DateTime;
    $dateFin = new DateTime;
    $datePremierContact = new DateTime;

    $dateDebut = date_date_set($dateDebut, $node->dateDebut['year'], $node->dateDebut['month'], $node->dateDebut['day']);
    $dateDebutTS = $dateDebut->getTimestamp();

    $dateFin = date_date_set($dateFin, $node->dateFin['year'], $node->dateFin['month'], $node->dateFin['day']);
    $dateFinTS = $dateFin->getTimestamp();

    $datePremierContact = date_date_set($datePremierContact, $node->datePremierContact['year'], $node->datePremierContact['month'], $node->datePremierContact['day']);
    $datePremierContactTS = $dateDebut->getTimestamp();


    $insert = db_insert('osa_affaire')
        ->fields(array(
          'nid' => $nid,
          'uid' => $uid,
          'idAffaire' => $node->idAffaire,
          'idClient' => $node->idClient,
          'titreAffaire' => $node->titreAffaire,
          'recapitulatif' => $node->recapitulatif,
          'prixHT' => $node->prixHT,
          'tva' => $node->tva,
          'sommeFrais' => $node->sommeFrais,
          'nbJEH' => $node->nbJEH,
          'prixJEH' => $node->prixJEH,
          'pourcentPrevi' => $node->pourcentPrevi,
          'sommeHTPrevi' => $node->sommeHTPrevi,
          'accompte' => $node->accompte,
          'soldeFinal' => $node->soldeFinal,
          'dateDebut' => $dateDebutTS,
          'dateFin' => $dateFinTS,
          'datePremierContact' => $datePremierContactTS,
          'origine' => $node->origine,
          'chartreQualite' => $node->chartreQualite,))
        ->execute();
  }
  elseif ($node->type == 'osa_client') {

    global $user;
    $nid = $node->nid;
    $uid = $user->uid;

    $insert = db_insert('osa_client')
        ->fields(array(
          'nid' => $nid,
          'uid' => $uid,
          'idClient' => $node->idClient,
          'nomClient' => $node->nomClient,
          'prenomClient' => $node->prenomClient,
          'fonction' => $node->fonction,
          'entreprise' => $node->entreprise,
          'numeroDeVoie' => $node->numeroDeVoie,
          'voie' => $node->voie,
          'codePostal' => $node->codePostal,
          'ville' => $node->ville,
          'mail' => $node->mail,
          'tel' => $node->tel,
          'commentaire' => $node->commentaire,
        ))
        ->execute();
  }
  else {
    return;
  }
}

/**
 * Implement hook_node_update()
 */
function osa_node_update($node) {
  // if we're not updating one of our own get out of here
  if ($node->type == "osa_affaire") {

    $update = db_update('osa_affaire')
        ->fields(array(
          'idAffaire' => $node->idAffaire,
          'idClient' => $node->idClient,
          'titreAffaire' => $node->titreAffaire,
          'recapitulatif' => $node->recapitulatif,
          'prixHT' => $node->prixHT,
          'tva' => $node->tva,
          'sommeFrais' => $node->sommeFrais,
          'nb' => $node->nbJEH,
          'prixJEH' => $node->prixJEH,
          'pourcentPrevi' => $node->pourcentPrevi,
          'sommeHTPrevi' => $node->sommeHTPrevi,
          'accompte' => $node->accompte,
          'soldeFinal' => $node->soldeFinal,
          'dateDebut' => $node->dateDebut,
          'dateFin' => $node->dateFin,
          'datePremierContact' => $node->datePremierContact,
          'origine' => $node->origine,
          'chatreQualite' => $node->chartreQualite,))
        ->condition('nid', $node->nid, '=')
        ->execute();
  }
  elseif ($node->type == "osa_client") {
    $update = db_update('osa_client')
        ->fields(array(
          'idClient' => $node->idClient,
          'nomClient' => $node->nomClient,
          'prenomClient' => $node->prenomClient,
          'fonction' => $node->fonction,
          'entreprise' => $node->entreprise,
          'numeroDeVoie' => $node->numeroDeVoie,
          'voie' => $node->voie,
          'codePostal' => $node->codePostal,
          'ville' => $node->ville,
          'mail' => $node->mail,
          'tel' => $node->tel,
          'commentaire' => $node->commentaire,
        ))
        ->condition('nid', $node->nid, '=')
        ->execute();
  }
}

/**
 * Implements hook_node_view().
 */
function osa_node_view($node, $view_mode, $langcode) {

  if (($node->type == 'osa_affaire')) {
    // get the data we want to display
    $data = db_select('osa_affaire', 'd')
        ->fields('d', array(
          'uid',
          'idAffaire',
          'idClient',
          'titreAffaire',
          'recapitulatif',
          'prixHT',
          'tva',
          'sommeFrais',
          'nbJEH',
          'prixJEH',
          'pourcentPrevi',
          'sommeHTPrevi',
          'accompte',
          'soldeFinal',
          'dateDebut',
          'dateFin',
          'datePremierContact',
          'origine',
          'chartreQualite',))
        ->condition("d.nid", $node->nid)
        ->execute()
        ->fetchAssoc();
    // fetch the user's name using {osa_data}.uid
    $user_name = db_select('users', 'u')
        ->fields('u', array('name'))
        ->condition("u.uid", $data['uid'])
        ->execute()
        ->fetchField();

    $idAffaire = $data['idAffaire'];
    $idClient = $data['idClient'];
    $titreAffaire = $data['titreAffaire'];
    $recapitulatif = $data['recapitulatif'];
    $prixHT = $data['prixHT'];
    $tva = $data['tva'];
    $sommeFrais = $data['sommeFrais'];
    $nbJEH = $data['nbJEH'];
    $prixJEH = $data['prixJEH'];
    $pourcentPrevi = $data['pourcentPrevi'];
    $sommeHTPrevi = $data['sommeHTPrevi'];
    $accompte = $data['accompte'];
    $soldeFinal = $data['soldeFinal'];
    $dateDebut = $data['dateDebut'];
    $dateFin = $data['dateFin'];
    $datePremierContact = $data['datePremierContact'];
    $origine = $data['origine'];
    $chartreQualite = $data['chartreQualite'];


    $dateDebutFormat = formatDateFR($dateDebut);
    $dateFinFormat = formatDateFR($dateFin);
    $datePremierContactFormat = formatDateFR($datePremierContact);

    // add what we want to the node content area
    $node->content['intro'] = array(
      '#markup' => '<p>This node was created by user ' . $user_name . '. Thanks for your contribution.</p>',
      '#weight' => -10,
    );
    $node->content['idAffaire'] = array(
      '#markup' => '<p><strong>ID de l\'affaire : ' . $idAffaire . '</strong></p>'
    );
    $node->content['email'] = array(
      '#markup' => '<p><strong>Example Email:</strong> ' . $idClient . '</p>',
      '#weight' => -9,
    );
    $node->content['plain_text'] = array(
      '#markup' => '<p><strong>The plain text:</strong> ' . $titreAffaire . '
                  avec pour date ' . $dateDebutFormat[0] . $dateDebutFormat[1] . $dateDebutFormat[2] . '</p>',
      '#weight' => -8,
    );
  }
  elseif ($node->type == 'osa_client') {
    $data = db_select('osa_client', 'c')
        ->fields('c', array(
          'uid',
          'idClient',
          'nomClient',
          'prenomClient',
          'fonction',
          'entreprise',
          'numeroDeVoie',
          'voie',
          'codePostal',
          'ville',
          'mail',
          'tel',
          'commentaire',))
        ->condition("c.nid", $node->nid)
        ->execute()
        ->fetchAssoc();
    // fetch the user's name using {osa_data}.uid
    $user_name = db_select('users', 'u')
        ->fields('u', array('name'))
        ->condition("u.uid", $data['uid'])
        ->execute()
        ->fetchField();

    $idClient = $data['idClient'];
    $nomClient = $data['nomClient'];
    $prenomClient = $data['prenomClient'];
    $fonction = $data['fonction'];
    $entreprise = $data['entreprise'];
    $numeroDeVoie = $data['numeroDeVoie'];
    $voie = $data['voie'];
    $codePostal = $data['codePostal'];
    $ville = $data['ville'];
    $mail = $data['mail'];
    $tel = $data['tel'];
    $commentaire = $data['commentaire'];

    // add what we want to the node content area
    $node->content['intro'] = array(
      '#markup' => '<p>This node was created by user ' . $user_name . ' pour le client ' . $idClient .
      ', de l\'entreprise ' . $entreprise . '</p>',
      '#weight' => -10,
    );
    $node->content['idAffaire'] = array(
      '#markup' => '<p><strong>Contact : ' . $nomClient . ' ' . $prenomClient . '</strong></p>'
    );
    $node->content['email'] = array(
      '#markup' => '<p><strong>Example Email:</strong> ' . $mail . '</p>',
      '#weight' => -9,
    );
    $node->content['plain_text'] = array(
      '#markup' => '<p><strong>The plain text:</strong> ' . $commentaire . '</p>',
      '#weight' => -8,
    );
  }
  else {
    return;
  }
}


///**
// * Implements hook_node_validate().
// */
//function osa_client_node_validate($node, $form, &$form_state) {
//  // if we're not validating one of our own get out of here
//  if ($node->type != "osa_client") {
//    return;
//  }
//  // Check to see if email address is formatted correctly
////	if (isset($node->osa_textfield) && !valid_email_address($node->osa_textfield))  {
////		form_set_error('osa_textfield', t('Please enter a valid email address.'), NULL);
////	}
//}
//
///**
// * Implement hook_node_insert()
// */
//function osa_client_node_insert($node) {
//  // if we're not inserting one of our own get out of here
//  if ($node->type != "osa_client") {
//    return;
//  }
//  global $user;
//  $nid = $node->nid;
//  $uid = $user->uid;
//
//  $insert = db_insert('osa_client')
//      ->fields(array(
//        'nid' => $nid,
//        'uid' => $uid,
//        'idClient' => $node->idClient,
//        'nomClient' => $node->nomClient,
//        'prenomClient' => $node->prenomClient,
//        'fonction' => $node->fonction,
//        'entreprise' => $node->entreprise,
//        'numeroDeVoie' => $node->numeroDeVoie,
//        'voie' => $node->voie,
//        'codePostal' => $node->codePostal,
//        'ville' => $node->ville,
//        'mail' => $node->mail,
//        'tel' => $node->tel,
//        'commentaire' => $node->commentaire,
//      ))
//      ->execute();
//}
//
///**
// * Implement hook_node_update()
// */
//function osa_client_node_update($node) {
//  // if we're not updating one of our own get out of here
//  if ($node->type != "osa_client") {
//    return;
//  }
//
//  $update = db_update('osa_client')
//      ->fields(array(
//        'idClient' => $node->idClient,
//        'nomClient' => $node->nomClient,
//        'prenomClient' => $node->prenomClient,
//        'fonction' => $node->fonction,
//        'entreprise' => $node->entreprise,
//        'numeroDeVoie' => $node->numeroDeVoie,
//        'voie' => $node->voie,
//        'codePostal' => $node->codePostal,
//        'ville' => $node->ville,
//        'mail' => $node->mail,
//        'tel' => $node->tel,
//        'commentaire' => $node->commentaire,
//      ))
//      ->condition('nid', $node->nid, '=')
//      ->execute();
//}
//
///**
// * Implements hook_node_view().
// */
//function osa_client_node_view($node, $view_mode, $langcode) {
//  if ($node->type != 'osa_client') {
//    return;
//  }
//  // get the data we want to display
//  $data = db_select('osa_client', 'c')
//      ->fields('c', array(
//        'uid',
//        'idClient',
//        'nomClient',
//        'prenomClient',
//        'fonction',
//        'entreprise',
//        'numeroDeVoie',
//        'voie',
//        'codePostal',
//        'ville',
//        'mail',
//        'tel',
//        'commentaire',))
//      ->condition("c.nid", $node->nid)
//      ->execute()
//      ->fetchAssoc();
//  // fetch the user's name using {osa_data}.uid
//  $user_name = db_select('users', 'u')
//      ->fields('u', array('name'))
//      ->condition("u.uid", $data['uid'])
//      ->execute()
//      ->fetchField();
//
//  $idClient = $data['idClient'];
//  $nomClient = $data['nomClient'];
//  $prenomClient = $data['prenomClient'];
//  $fonction = $data['fonction'];
//  $entreprise = $data['entreprise'];
//  $numeroDeVoie = $data['numeroDeVoie'];
//  $voie = $data['voie'];
//  $codePostal = $data['codePostal'];
//  $ville = $data['ville'];
//  $mail = $data['mail'];
//  $tel = $data['tel'];
//  $commentaire = $data['commentaire'];
//
//  // add what we want to the node content area
//  $node->content['intro'] = array(
//    '#markup' => '<p>This node was created by user ' . $user_name . ' pour le client ' . $idClient .
//    ', de l\'entreprise ' . $entreprise . '</p>',
//    '#weight' => -10,
//  );
//  $node->content['idAffaire'] = array(
//    '#markup' => '<p><strong>Contact : ' . $nomClient . ' ' . $prenomClient . '</strong></p>'
//  );
//  $node->content['email'] = array(
//    '#markup' => '<p><strong>Example Email:</strong> ' . $mail . '</p>',
//    '#weight' => -9,
//  );
//  $node->content['plain_text'] = array(
//    '#markup' => '<p><strong>The plain text:</strong> ' . $commentaire . '</p>',
//    '#weight' => -8,
//  );
//}